### ISSUE TITLE
Issue with 33-challenge-sealed-classes folder name

### ISSUE THREAD

**Issue by paulio84** [kodecocodes/video-pikfc-materials#1]
When I try to clone the repository I get the following error in the terminal

error: invalid path '33-challenge-sealed-classes /.idea/.gitignore'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

It looks to me like there is a space character at the end of the directory name "33-challenge-sealed-classes ".

If I download the zip file I can see an underscore character at the end of the directory name, and in the URL in the browser I see a %20, indicating a space character.  I can continue by using the downloaded zip file, but cloning the repository cause my error.

**Comment by jellodiil** [comment]
Hi @paulio84 , thanks for pointing this out!
I have updated the directory name so it doesn't have the space anymore — hopefully has fixed the error!
